### ISSUE TITLE
Xcode4 configuration build fails with "would be excluded by the rule to exclude" error

### ISSUE THREAD

**Issue by jazzbre** [bkaradzic/GENie#220] opened 2016-07-20 06:00 UTC
Just updated to the latest genie and when building configuration for xcode I get:

Running action 'xcode4'...

stack traceback:
    [C]: in function 'error'
    [string "premake.xcode.parameters = { }..."](604:):604: in local 'verify_file'
    [string "premake.xcode.parameters = { }..."](604:):615: in upvalue 'cfg_excluded_files'
    [string "premake.xcode.parameters = { }..."](604:):648: in field 'XCBuildConfiguration_Project'
    [string "premake.xcode.parameters = { }..."](604:):737: in field 'XCBuildConfiguration'
    [string "local xcode = premake.xcode..."]:110: in local 'callback'
    [string "premake._filelevelconfig = false..."]:5: in field 'generate'
    [string "premake.xcode = { }..."]:66: in field 'onproject'
    [string "premake.action = { }..."]:23: in field 'call'
    [string "_WORKING_DIR        = os.getcwd()..."]:82: in function '_premake_main'
make: **\* [projgen] Error 1

I'm attaching build scripts used if anyone has any idea why this happens.
Thanks!

[scripts.zip](https://github.com/bkaradzic/GENie/files/372929/scripts.zip)

**Comment by bkaradzic** [comment] 2016-07-20 15:53
Did this work with previous version of GENie?

**Comment by jazzbre** [comment] 2016-07-20 16:26
Yes it did, but I'll post the last working commit later when I have time to try it.

**Comment by jazzbre** [comment] 2016-07-20 17:05
It stopped working with this commit in BX repo:
https://github.com/bkaradzic/bx/commit/05323ca165260251f1bc61018c060521b2811195

**Comment by bkaradzic** [comment] 2016-07-20 17:41
What's the version of GENie?

**Comment by jazzbre** [comment] 2016-07-20 18:15
Last working:
GENie - Project generator tool version 562 (commit 1f68760c8c1f561deda5d1601aee86330f6ef4e5)
First non-working:
GENie - Project generator tool version 564 (commit 69e70a3d9e3f04752aa8f61d453a7c915b8dea67)

**Comment by rhoot** [comment] 2016-07-20 19:26
The problem is the way that files are added to projects. I recently added support for files to be added per configuration rather than only globally per project. So you can do:
```lua
files {"foo.cpp"}
configuration {"Debug"}
    files {"bar.cpp"}
```
foo.cpp would be added globally, while bar.cpp would only be added for the Debug configuration, and implicitly excluded in others.

This poses a problem with XCode projects, where you can only exclude files based on their filename. Imagine that you have:
```lua
configurations {"Debug", "Release"}
files {"src/a/foo.cpp"}
configuration {"Debug"}
    files {"src/b/foo.cpp"}
```
In the Debug configuration you would have src/a/foo.cpp and src/b/foo.cpp, with no files excluded. In Release however, you would have the same two files, but the latter would be excluded from the build. But since - in XCode - you can only exclude files by filenames and not paths, there's no way for the project to exclude the latter without also excluding the former. That's what this error tells you about.

The error message should tell you the full path of the file about to be excluded when it wasn't supposed to be. Could you paste that message? It should be above the callstack in the error output, and would make it easier to track down the exact problem when looking at your script files.

**Comment by bkaradzic** [comment] 2016-07-20 19:41
This bug exist in bx too `genie xcode4`, you can try it there.

**Comment by jazzbre** [comment] 2016-07-21 13:33
This is the error (If I paste it in here it doesn't show completely):
[error.txt](https://github.com/bkaradzic/GENie/files/376088/error.txt)

The scripts to reproduce this are included in initial comment.
Thanks!

**Comment by KageKirin** [comment] 2016-08-30 07:41
Got the same error (version 614):
genie/src/actions/xcode/xcode_common.lua:841, function `local function verify_file(file)`

In my case, it's the project configuration with wildcards in `excludes{}`.

In detail:
```
local boost_thread = {"thread"}
	project "boost.thread"
		kind "StaticLib"

		includedirs {
			boost_includedirs,
			gen_boost_dirs(boost_thread, boost_libs_root, "src")
		}

		defines {
			boost_defines,
		}


		files {
			gen_boost_dirs(boost_thread, boost_libs_root, "src/**.h"),
			gen_boost_dirs(boost_thread, boost_libs_root, "src/**.hpp"),
			gen_boost_dirs(boost_thread, boost_libs_root, "src/**.ipp"),
			gen_boost_dirs(boost_thread, boost_libs_root, "src/**.inc"),
			gen_boost_dirs(boost_thread, boost_libs_root, "src/**.inl"),
			gen_boost_dirs(boost_thread, boost_libs_root, "src/**.cpp"),
		}

		excludes {
			boost_excludes, -- <-- this guy, contains wildcards
		}

		buildoptions {
			cpp14_buildoptions,
		}

		linkoptions {
			cpp14_linkoptions,
		}
```

with `boost_excludes` defined as follows:

```
boost_excludes = {
	path.join(boost_libs_root, "context/src/unsupported.cpp"),
	path.join(boost_libs_root, "regex/build/**.cpp"), -- <-- many many wildcards b/c I'm lazy
	path.join(boost_libs_root, "*/build/**.cpp"),
	path.join(boost_libs_root, "iostreams/src/gzip.cpp"),
	path.join(boost_libs_root, "iostreams/src/bzip2.cpp"),
	path.join(boost_libs_root, "locale/src/icu/**.cpp"),
	path.join(boost_libs_root, "log/src/dump_ssse3.*"),
	path.join(boost_libs_root, "log/src/dump_avx2.*"),
	path.join(boost_libs_root, "mpi/src/python/**.*"),
}

-- per-platform excludes
if isWinBuild() then
	boost_excludes = mergeTables(boost_excludes, {
		path.join(boost_libs_root, "coroutine/src/detail/standard_stack_allocator_posix.cpp"),
		path.join(boost_libs_root, "coroutine/src/detail/segmented_stack_allocator.cpp"),
		path.join(boost_libs_root, "locale/src/posix/**.*"),
		path.join(boost_libs_root, "thread/src/pthread/**.*"),
	})
else
	boost_excludes = mergeTables(boost_excludes, {
		path.join(boost_libs_root, "coroutine/src/detail/standard_stack_allocator_windows.cpp"),
		path.join(boost_libs_root, "coroutine/src/detail/segmented_stack_allocator.cpp"),
		path.join(boost_libs_root, "locale/src/win32/**.*"),
		path.join(boost_libs_root, "log/src/debug_output_backend.cpp"),
		path.join(boost_libs_root, "log/src/light_rw_mutex.cpp"),
		path.join(boost_libs_root, "thread/src/win32/**.*"),
	})
end
```

Note: this was working before with version 556, but I'm fixing the luafile now.

**Comment by bkaradzic** [comment] 2016-08-30 17:04
Probably related to this: https://github.com/bkaradzic/GENie/pull/211? (cc @rhoot)

**Comment by rhoot** [comment] 2016-09-24 07:48
Oh sorry, for some reason I was not emailed notifications about this thread.

@jazzbre, thanks for the error message. I had a quick look at the scripts. What's happening is that sdl.lua contains blocks of files that are configuration specific. What *used* to happen is that these `files` blocks would (in most cases) be ignored, since `files` was only valid on a project-wide level. To quote the [documentation](https://github.com/bkaradzic/genie/blob/master/docs/scripting-reference.md#filesfiles): *"May be set on the solution, project, or configuration, but only project-level file lists are currently supported."*

#208 changed that so they can be added per configuration instead. What actually happens now is that this:
```lua
files { "a.cpp", "b.cpp" }
configuration { "xcode4" }
    files { "c.cpp" }
```
Is equivalent of doing:
```lua
files { "a.cpp", "b.cpp", "c.cpp" }
configuration { "not xcode4" }
    excludes { "c.cpp" }
```

The particular problem here is that all the platforms defined in sdl.lua have files that have the same names, so you end up with implicit `excludes` blocks that contains a file with the same name as a file that is included in the build. Again, since XCode only supports excluding files based on file name that's not something GENie can support.

I don't know that there's an easy way to fix this, but I'll look a bit more closely in the upcoming few days. We could back out #208 but then you're back to relying on unsupported behavior. I'm actually still trying to figure out why this used to work for you in the first place.

@KageKirin, your problem is unrelated (aside from the error message). This error is meant to tell you you're about to shoot yourself in the foot. Your `files` block is including a file with the same name as one of the files in your `excludes` block (probably due to the wildcards). There's no way to support this in XCode.

**Comment by o7alesmlakar** [comment] 2016-12-18 09:02
I have to update to latest commit because I need OSX Bundles. @rhoot any idea how to get around this problem?
I guess turning everything around and do excludes wouldn't help here, right?

It seems I only have this problem on OpenAL and SDL. So I would be able to make split .lua files for different configurations. 
Like sdl_osx.lua, sdl_ios.lua and sdl.lua for all other platforms since this problem only affects xcode it seems.

Something like this would work:
`
if _ACTION == "xcode4" then
	if _XCODE == "ios"
		dofile("sdl_ios.lua")
	else
		dofile("sdl_osx.lua")	
	end
else
	dofile("sdl.lua")	
end
`
But I don't know how to differentiate between iOS and OSX (I just made up that _XCODE parameter), so that's the only problem.

**Comment by rhoot** [comment] 2016-12-21 09:33
I did some experimenting and found that XCode *does* support paths in exclude filenames, just not relative paths. I submitted a PR (#264) that makes the excludes thing much more lenient with what it can and cannot accept.

Could you try it after it's been merged/built, to see if it resolves your specific problem? Alternately pull the PR and build it yourself.

**Closed** 2016-12-21 16:21 UTC

**Comment by o7alesmlakar** [comment] 2016-12-22 07:44
Thanks @rhoot, It works!
